learningequality/kolibri-installer-windows

windows/installer-source/KolibriSetupScript.iss, windows/scripts/uninstall-kolibri.bat
I created a script to uninstall kolibri static during uninstallation.
This fixes #15 
##
Here's the [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMMklsYmVuR1FCU0U) to test this PR.
/cc @radinamatic @mrpau-eduard
=> Uninstall kolibri static when uninstalling kolibri.

windows/inno-compiler/Default.isl, windows/inno-compiler/Languages/French.isl, windows/inno-compiler/Languages/German.isl, windows/inno-compiler/Languages/Greek.isl, windows/inno-compiler/Languages/Nepali.islu, windows/inno-compiler/Languages/Portuguese.isl, windows/inno-compiler/Languages/Spanish.isl, windows/installer-source/KolibriSetupScript.iss
I updated the inno setup isl strings and also update the kolibri Windows installer crowdin.
Here's the [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMODZ2TWlhUFVyTVk) to test this PR.
This fixes #41 
cc/ @radinamatic @indirectlylit
=> Launch kolibri is not translated.

windows/inno-compiler/Default.isl
This fixes the conflicts at the default isl file. 
The develop branch will fail to build because of these conflicts.
=> Fix default isl file conflicts.

windows/inno-compiler/Default.isl, windows/inno-compiler/Languages/French.isl, windows/inno-compiler/Languages/German.isl, windows/inno-compiler/Languages/Greek.isl, windows/inno-compiler/Languages/Nepali.islu, windows/inno-compiler/Languages/Portuguese.isl, windows/inno-compiler/Languages/Spanish.isl, windows/installer-source/KolibriSetupScript.iss, windows/python-setup/python-exe.bat
This fixes #67, [#5571](https://github.com/learningequality/ka-lite-installers/issues/475) and [#66](https://github.com/learningequality/kolibri-installer-windows/issues/66)
Here's the [installer](https://drive.google.com/open?id=1iTrBTWLJlaqG84hgCkNvwvKtCt86GmH7) to test this.
cc @radinamatic @benjaoming @indirectlylit
=> Update built in Python installer from 2.7.13 into 3.4.3

windows/python-setup/python-exe.bat
ought to contain the same content as #103
refs #102
=> Add the python path to environment variables - alternate branch

windows/inno-compiler/Languages/Spanish.isl
committed using windows endlines and Windows-1252 encoding
=> spanish translations for uninstaller

windows/inno-compiler/Languages/Spanish.isl
=> add missing strings

CHANGELOG.md, README.md
I updated the `README.md`  and `CHANGELOG.md` for the v1.3.3 release.
=> Update README.md  and CHANGELOG.md for the v1.3.3

CHANGELOG.md, README.md
I updated the README.md and the CHANGELOG.md for the v1.3.4 release
=> I updated the README.md and the CHANGELOG.md for the v1.3.4 release

CHANGELOG.md, README.md
I updated the CHANGELOG and README.md for 1.3.5 release
=> Update CHANGELOG and README for 1.3.5 release

src/installer-source/KolibriSetupScript.iss
This fix the error on BuildKite
=> Fix HandlePythonSetup error.

src/installer-source/KolibriSetupScript.iss, src/python-setup/python-exe.bat
This fixes #161 
I added the kolibri command to Windows Path after the Pip installation.
=> Add kolibri command to Windows Path.

src/installer-and-application-po-files/innosetup-brazilian-portuguese.po, src/installer-and-application-po-files/innosetup-english-customized-strings.po, src/installer-and-application-po-files/innosetup-english.po, src/installer-and-application-po-files/innosetup-french.po, src/installer-and-application-po-files/innosetup-italian.po, src/python-scripts/en-template.json, src/python-scripts/extract-translated.py
I extracted the translated InnoSetup isl to po file. To upload it at the Crowdin.
REF: https://jrsoftware.org/files/istrans/
cc @radinamatic
=> Extract translated InnoSetup Isl to po file

src/Makefile
I updated the Makefile Python version
=> Update makefile Python version

src/Makefile
I forgot to update the  Python md5sum
=> Update Makefile Python md5sum

src/installer-and-application-po-files/innosetup-customized.po, src/installer-and-application-po-files/kolibri-application.po, src/python-scripts/innosetup.po
I updated the Kolibri Windows `po` files strings.
@radinamatic requested to update these strings on [Slack](https://learningequality.slack.com/archives/CAUTAU14Y/p1592890502079000?thread_ts=1592883627.078000&cid=CAUTAU14Y)
=> Update po files

src/installer-and-application-po-files/innosetup.po
I added this old string in my first PR  #174 and should be remove.
=> Remove old strings in the innosetup.po file

README.md, src/python-scripts/encode-strings.py
work on string encoding script
=> encode from isl to po

src/gui-source/Kolibri/Kolibri.cpp
Reverts learningequality/kolibri-installer-windows#190
=> Revert "Remove second call to getline"

README.md, src/installer-source/KolibriSetupScript.iss
* Update inno setup to set installer env vars.
* Update readme.
Fixes #186
=> Set installation env vars at install
